// Code generated by protoc-gen-gogo.
// source: github.com/fd/featherhead/tools/runtime/svchttp/annotations.proto
// DO NOT EDIT!

/*
Package svchttp is a generated protocol buffer package.

It is generated from these files:
	github.com/fd/featherhead/tools/runtime/svchttp/annotations.proto
	github.com/fd/featherhead/tools/runtime/svchttp/http_rule.proto

It has these top-level messages:
	HttpRule
*/
package svchttp

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var E_ApiHost = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         58801,
	Name:          "xyz.featherhead.api.api_host",
	Tag:           "bytes,58801,opt,name=api_host",
}

var E_Http = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MethodOptions)(nil),
	ExtensionType: (*HttpRule)(nil),
	Field:         58800,
	Name:          "xyz.featherhead.api.http",
	Tag:           "bytes,58800,opt,name=http",
}

var E_HideInSwagger = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         58810,
	Name:          "xyz.featherhead.api.hideInSwagger",
	Tag:           "varint,58810,opt,name=hideInSwagger",
}

var E_Format = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         58811,
	Name:          "xyz.featherhead.api.format",
	Tag:           "bytes,58811,opt,name=format",
}

func init() {
	proto.RegisterExtension(E_ApiHost)
	proto.RegisterExtension(E_Http)
	proto.RegisterExtension(E_HideInSwagger)
	proto.RegisterExtension(E_Format)
}
