// Code generated by protoc-gen-gogo.
// source: github.com/fd/featherhead/tools/runtime/svcauth/annotations.proto
// DO NOT EDIT!

/*
Package svcauth is a generated protocol buffer package.

It is generated from these files:
	github.com/fd/featherhead/tools/runtime/svcauth/annotations.proto
	github.com/fd/featherhead/tools/runtime/svcauth/authn.proto
	github.com/fd/featherhead/tools/runtime/svcauth/authz.proto
	github.com/fd/featherhead/tools/runtime/svcauth/desc.proto

It has these top-level messages:
	AuthnRule
	AuthzRule
	AuthDescription
	AuthDescriptionSet
*/
package svcauth

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var E_Authn = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MethodOptions)(nil),
	ExtensionType: (*AuthnRule)(nil),
	Field:         58700,
	Name:          "xyz.featherhead.api.authn",
	Tag:           "bytes,58700,opt,name=authn",
}

var E_Authz = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MethodOptions)(nil),
	ExtensionType: (*AuthzRule)(nil),
	Field:         58701,
	Name:          "xyz.featherhead.api.authz",
	Tag:           "bytes,58701,opt,name=authz",
}

var E_DefaultAuthn = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*AuthnRule)(nil),
	Field:         58700,
	Name:          "xyz.featherhead.api.default_authn",
	Tag:           "bytes,58700,opt,name=default_authn",
}

var E_DefaultAuthz = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*AuthzRule)(nil),
	Field:         58701,
	Name:          "xyz.featherhead.api.default_authz",
	Tag:           "bytes,58701,opt,name=default_authz",
}

func init() {
	proto.RegisterExtension(E_Authn)
	proto.RegisterExtension(E_Authz)
	proto.RegisterExtension(E_DefaultAuthn)
	proto.RegisterExtension(E_DefaultAuthz)
}
