// Code generated by protoc-gen-gogo.
// source: github.com/fd/featherhead/tools/runtime/svcauth/desc.proto
// DO NOT EDIT!

package svcauth

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type AuthDescription struct {
	Method string     `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Authn  *AuthnRule `protobuf:"bytes,2,opt,name=authn" json:"authn,omitempty"`
	Authz  *AuthzRule `protobuf:"bytes,3,opt,name=authz" json:"authz,omitempty"`
}

func (m *AuthDescription) Reset()         { *m = AuthDescription{} }
func (m *AuthDescription) String() string { return proto.CompactTextString(m) }
func (*AuthDescription) ProtoMessage()    {}

func (m *AuthDescription) GetAuthn() *AuthnRule {
	if m != nil {
		return m.Authn
	}
	return nil
}

func (m *AuthDescription) GetAuthz() *AuthzRule {
	if m != nil {
		return m.Authz
	}
	return nil
}

type AuthDescriptionSet struct {
	Methods []*AuthDescription `protobuf:"bytes,1,rep,name=methods" json:"methods,omitempty"`
}

func (m *AuthDescriptionSet) Reset()         { *m = AuthDescriptionSet{} }
func (m *AuthDescriptionSet) String() string { return proto.CompactTextString(m) }
func (*AuthDescriptionSet) ProtoMessage()    {}

func (m *AuthDescriptionSet) GetMethods() []*AuthDescription {
	if m != nil {
		return m.Methods
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthDescription)(nil), "xyz.featherhead.api.AuthDescription")
	proto.RegisterType((*AuthDescriptionSet)(nil), "xyz.featherhead.api.AuthDescriptionSet")
}
