// Code generated by protoc-gen-gogo.
// source: github.com/fd/featherhead/tools/runtime/sql/annotations.proto
// DO NOT EDIT!

/*
Package sql is a generated protocol buffer package.

It is generated from these files:
	github.com/fd/featherhead/tools/runtime/sql/annotations.proto
	github.com/fd/featherhead/tools/runtime/sql/sql.proto

It has these top-level messages:
	ModelDescriptor
	ColumnDescriptor
	ScannerDescriptor
	JoinDescriptor
*/
package sql

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var E_Model = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*ModelDescriptor)(nil),
	Field:         58900,
	Name:          "xyz.featherhead.api.model",
	Tag:           "bytes,58900,opt,name=model",
}

var E_Column = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*ColumnDescriptor)(nil),
	Field:         58910,
	Name:          "xyz.featherhead.api.column",
	Tag:           "bytes,58910,opt,name=column",
}

var E_Join = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*JoinDescriptor)(nil),
	Field:         58911,
	Name:          "xyz.featherhead.api.join",
	Tag:           "bytes,58911,opt,name=join",
}

func init() {
	proto.RegisterExtension(E_Model)
	proto.RegisterExtension(E_Column)
	proto.RegisterExtension(E_Join)
}
